"""
Reporting helpers for batch grading.

This module exports batch-grading results in:
- plain-text log format
- PDF visual report format

The PDF report uses annotated images generated by batch_visualization.
"""

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from PIL import Image

from batch_visualization import draw_overlay


def export_results_txt(txt_path, tests):
    """
    Export grading results as a human-readable text log.

    For each test, the output includes:
    - the test number
    - the final grade, if available
    - a per-question correctness log

    Parameters:
        txt_path (str): Destination path for the TXT file.
        tests (list[dict]): Detailed per-test grading data.
    """
    with open(txt_path, "w", encoding="utf-8") as f:
        for test in tests:
            if test["grade"] is None:
                f.write(f"test number {test['test_number']} has no matching solution key\n\n")
                f.write("=" * 60 + "\n\n")
                continue

            f.write(f"test number {test['test_number']} has grade {test['grade']}\n\n")
            f.write("Question log:\n\n")

            for q in test["questions"]:
                status = "correct" if q["is_correct"] else "incorrect"
                f.write(
                    f"Q{q['question_number']}: {status} | "
                    f"answer={q['answer']} | key={q['key']}\n\n"
                )

            f.write("=" * 60 + "\n\n")


def export_results_pdf(pdf_path, tests):
    """
    Export grading results as a visual PDF report.

    The first page contains a short legend. Each following page shows one test
    image with grading overlays drawn on top of the detected answer boxes.

    Parameters:
        pdf_path (str): Destination path for the PDF file.
        tests (list[dict]): Detailed per-test grading data including images and
            question/box information.
    """
    c = canvas.Canvas(pdf_path, pagesize=A4)
    page_w, page_h = A4

    # Title and legend page.
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, page_h - 50, "Batch Grading Visual Report")

    c.setFont("Helvetica", 12)
    c.drawString(50, page_h - 100, "White dots indicate boxes detected as colored.")
    c.drawString(50, page_h - 125, "Red dots indicate boxes detected as not colored.")
    c.drawString(50, page_h - 150, "Each following page shows one graded test.")
    c.showPage()

    for test in tests:
        # Draw the grading overlay on the original test image.
        annotated = draw_overlay(test["image_for_pdf"], test["questions"])

        # Convert the OpenCV/numpy-style image into a PIL image for ReportLab.
        rgb = annotated[:, :, ::-1]
        pil_img = Image.fromarray(rgb)
        reader = ImageReader(pil_img)

        iw, ih = pil_img.size
        scale = min((page_w - 40) / iw, (page_h - 40) / ih)

        draw_w = iw * scale
        draw_h = ih * scale
        x = (page_w - draw_w) / 2
        y = (page_h - draw_h) / 2

        c.drawImage(reader, x, y, width=draw_w, height=draw_h)
        c.showPage()

    c.save()
